---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 13759.
--- DateTime: 2024/12/30 11:03
---


local key = KEYS[1]

local zaddArgs = {}

for i = 1, #ARGV - 1,2 do
    table.insert(zaddArgs,ARGV[i])
    table.insert(zaddArgs,ARGV[i+1])
end

redis.call('ZADD',key,unpack(zaddArgs))

local expireSeconds = ARGV[#ARGV]
redis.call('EXPIRE',key,expireSeconds)

return 0 