---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 13759.
--- DateTime: 2024/12/29 16:43
---


local key = KEYS[1] -- 操作的 Redis Key
local noteId = ARGV[1] -- 笔记ID

-- 判断Bloom过滤器是否存在
local exist = redis.call('EXISTS',key)
if exist == 0 then
    return -1
end

-- 判断是否点赞过
local isLiked = redis.call('BF.EXISTS',key,noteId)
if isLiked == 1 then
    return 1
end

-- 点赞，添加到过滤器里
redis.call('BF.ADD',key,noteId)
return 0