---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 13759.
--- DateTime: 2024/12/30 13:57
---


local key = KEYS[1]
local noteId = ARGV[1]

local exist = redis.call('EXISTS',key)
-- 判断布隆过滤器是否存在
if exist == 0 then
    return -1
end

-- 判断是否点赞过
local isLiked = redis.call('BF.EXISTS',key,noteId)
-- 笔记未点赞（绝对没有误判）
if isLiked == 0 then
    return 2
end

-- 笔记已点赞（可能有误判）,落库时再处理
return 1

