---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 13759.
--- DateTime: 2024/12/30 10:34
---


local key = KEYS[1]
local noteId = ARGV[1]
local timestamp = ARGV[2]

-- 判断zset是否存在
local exist = redis.call('EXISTS',key)
if exist == 0 then
    return -1
end

-- 判断zset是否大于100
local count = redis.call('ZCARD',key)
if count >=100 then
    redis.call('ZPOPMIN',key)
end

redis.call('ZADD',key,timestamp,noteId)
return 0