---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 13759.
--- DateTime: 2024/12/23 10:28
---

local key = KEYS[1] -- redis的key
local followUserId = ARGV[1] --被关注用户的id
local time = ARGV[2] -- 时间戳

-- 使用EXIST命令检查key是否存在
local exist = redis.call('EXISTS',key)
if exist == 0 then
    return -1
end

-- 检查用户是否关注超过上限
local count  = redis.call("ZCARD",key)
if count >= 1000 then
    return -2
end

-- 判断是否已经关注
if redis.call('ZSCORE',key,followUserId) then
    return -3
end

-- 向redis中插入关注记录
redis.call('ZADD',key,time,followUserId)
return 0