---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 13759.
--- DateTime: 2024/12/24 10:01
---

local key = KEYS[1]
local unfollowUserId = ARGV[1]

-- 判断缓存是否存在
local exist = redis.call('EXISTS',key)
if exist ==0  then
    return -1
end

-- 存在则判断是否已经关注
local score =  redis.call('ZSCORE',key,unfollowUserId)
if score == false or score == nil then
    return -4
end

-- 存在则在缓存中删除该关注
redis.call('ZREM',key,unfollowUserId)
return 0